# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4



    
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  
  # Terraform Installation
    
      - name: Check Terraform
        run: terraform version

     # Terraform Init
    
      - name: Terraform init
        run: terraform init

    # Terraform fmt
    
      - name: Terraform fmt 
        run: terraform fmt 

        # Terraform validate
    
      - name: Terraform validate
        run: terraform validate 

        # Terraform plan
    
      - name: Terraform plan 
        run: terraform plan 