name: Run Azure Login with OIDC

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Dev Environment

    steps:

      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4

      # Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      # Check Terraform
      - name: Check Terraform
        run: terraform version

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Format
      - name: Terraform Format
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan